Dev
Gulyakov/pet_store_api_autotest pull request #2
Opened 2024-12-05 21:36 UTC by Gulyakov

Исправление замечаний

2024-12-05 22:15 UTC, Gulyakov commented on src/test/java/steps/base/CucumberHooks.java
> +    Memory.getInstance();
Для чего? Если и без создания экземпляра возможно хранить данные в map? @diinal

2024-12-06 12:43 UTC, softester-git commented on src/test/java/runners/CucumberTestRunner.java
> +
Сюда нужно ещё одно поле:
![image](https://github.com/user-attachments/assets/ac11dcaa-a536-416e-8279-3a35a996f1c5)

2024-12-06 12:43 UTC, softester-git commented on src/test/java/runners/CucumberTestRunner.java
> +
Этот @debug потом подставляется к тегам того сценария, который ты редактируешь и запускаешь

2024-12-06 12:45 UTC, softester-git commented on build.gradle
> +    testImplementation 'junit:junit:4.13.2'
Вот это скорее всего не понадобится

2024-12-06 13:38 UTC, Diinal commented on src/test/java/steps/base/CucumberHooks.java
> +    Memory.getInstance();
Потому что без создания жкземпляра ты не можешь гарантировать единственность экземпляра класса. А он у тебя отвечает за хранение данных.
грубо говоря это нужно чтобы у тебя всегда только одна мапа была с данными.
Это как раз реализация шаблона проектирования Singletone

2024-12-06 13:41 UTC, Diinal requested changes

2024-12-06 13:41 UTC, Diinal commented on src/test/java/steps/base/CucumberHooks.java
> +    Memory.clear();
лишнее, у тебя в афтер уже есть очистка

2024-12-10 13:46 UTC, softester-git commented on src/test/resources/features/addition.feature
> +Feature: Сложение двух чисел
Тут не хватает "шапки":
# encoding: UTF-8
# language: en

как во всех наших проектах, можно глянуть для примера

2024-12-10 13:51 UTC, softester-git commented on src/test/resources/features/addition.feature
> +Feature: Сложение двух чисел
![image](https://github.com/user-attachments/assets/08100791-f931-4b6c-856a-49696f2d4b69)

2024-12-13 08:40 UTC, softester-git approved these changes
Пожелания:
1. Обычно к тегам сценария добавляются что-то типа @smoke или @regress и тег @all
2. Прикрутить логирование (Класс Log в наших проектах), что бы логировать запросы и полученные ответы

Примеры есть у нас в java-проектах

2025-01-27 12:42 UTC, softester-git reviewed
Так же не забываем удаляеть неиспользуемые импорты (в UpdatePetSteps).
И жать CTRL+ALT+L в коде для автоформатирования.

2025-01-27 12:42 UTC, softester-git commented on src/test/java/steps/CommonSteps.java
> +import static io.restassured.RestAssured.given;
import static не используем. Вместо этого просто import класса и в коде вызов нужного метода через:
Class.method()

2025-01-27 12:42 UTC, softester-git commented on src/test/java/steps/CommonSteps.java
> +  public static Response getResponse() {
Данный метод относится к получению ответа на запрос. Подобным вспомогательным методам самое место в stephelpers. Например назвать можно stephelpers/Api.java и положить туда все методы для отправки и получения запросов

2025-01-27 12:42 UTC, softester-git commented on src/test/java/steps/CreatePetSteps.java
> +import static steps.CommonSteps.getResponse;
static не используем

2025-01-27 12:42 UTC, softester-git commented on src/test/java/steps/CreatePetSteps.java
> +  private String getPetNameFromRequest() {
Данный метод, как вспомогательный, тоже лучше вынести в stephelpers

2025-01-27 12:42 UTC, softester-git commented on src/test/java/steps/CommonSteps.java
Обычно в commonSteps хранятся только общие методы и поля. Остальное разносится по другим степсам, и называются эти другие степсы, как правило, не по названию задачи, а по областям применения. Можно посмотреть в наших проектах, например DbSteps, FtpSteps, ApiSteps(ResponseSteps, RequestSteps)  т.д.

2025-01-27 12:42 UTC, softester-git commented on src/test/java/steps/CommonSteps.java
> +    Log.log("Адрес запроса: " + Memory.get("baseURI") + endpoint);
Лучше не вызывать 2 раза Log, а в одном склеить 2 сообщения через System.lineSeparator()

2025-01-30 10:50 UTC, Gulyakov commented on src/test/java/steps/CommonSteps.java
> +    Log.log("Адрес запроса: " + Memory.get("baseURI") + endpoint);
Исправил

2025-01-30 10:50 UTC, Gulyakov commented on src/test/java/steps/CreatePetSteps.java
> +import static steps.CommonSteps.getResponse;
Исправил

2025-01-30 10:50 UTC, Gulyakov commented on src/test/java/steps/CommonSteps.java
> +import static io.restassured.RestAssured.given;
Исправил

2025-01-31 15:08 UTC, softester-git commented on src/test/resources/features/CreateOrder.feature
> +  @debug @All
Тег @debug лучше убрать из всех сценариев и оставить только All. 
@Debug лучше подставлять во время разработки в единтсвенный сценарий который правишь.
Так же нужно помимо All добавить теги например @CreatePet, @UpdatePet и т.д., т.е. в сценарии у нас получается 2 тега:
1. All для запуска всего списка сценариев
2. @Уникальный для проверки сценария, создания питомца например - @CreatePet

2025-01-31 15:09 UTC, softester-git approved these changes

2025-02-01 14:43 UTC, merged